### ISSUE TITLE
Handle vue / vbuild directly

### ISSUE THREAD

**Issue by icarito** [manatlan/wuy#11]
It'd be great not to have to override _render method in order to use vue / vbuild. Perhaps with a constructor parameter? Just an idea!

**Comment by manatlan** [comment]
I'd like to have hotreload ...
But I'm asking myself, how to maintain the WebSocket connection ?
Is devtools supposed to do this kind of thing ?

Le mar. 29 janv. 2019 à 05:33, Sebastian Silva <notifications@github.com> a
écrit :
