### ISSUE TITLE
Wish: Hot reload on source file changed

### ISSUE THREAD

**Issue by icarito** [manatlan/wuy#2]
I've seen this either with a full reload or just the updated module in question.

I sometimes work this way with Rapyscriptify + Browserify + Budo (e.g. see https://gitlab.com/fuentelibre/forest-heroes where it's setup to `npm run live`).

It would be super cool to avoid to have to stop / start the server each time, while developing.

Thanks for this, it's super cool!
Regards,

Sebastian

**Comment by icarito** [comment]
i.e. when you run type `npm run live` and then go and change a source file it will automatically reload the javascript module in the browser.

**Comment by icarito** [comment]
Thanks for keeping this one open! I'm using currently using [aiohttp-devtools](https://pypi.org/project/aiohttp-devtools) for hot-reloading static projects. I tried using it with Wuy but it seems to require access to starting the aiohttp app.

**Comment by manatlan** [comment]
Hi @icarito ...
Next version of [guy](https://github.com/manatlan/guy) will support autoreload ootb ;-)
It works as expected ... I'm polishing it and release it soon

**Comment by manatlan** [comment]
done !

The 0.5.1 does autoreload ... by providing `app.run(autoreload=True)` (same for .serve(), same for .runCef() )

**Comment by icarito** [comment]
Exciting! Thank you for the heads up, I'll try it!

**Comment by icarito** [comment]
I made a patch to fix watching static assets, thank you!

**Comment by icarito** [comment]
See https://github.com/manatlan/guy/pull/8

**Comment by icarito** [comment]
I was able to get this to work with _run_ but not for _serve_ for some reason

**Comment by manatlan** [comment]
@icarito 
your patch is in 0.5.3 ;-)

> I was able to get this to work with run but not for serve for some reason

strange, seems to work on hy host ...

BTW, the autoreload on glitch.com is a non-sense ... because glitch does the autoreloading process natively ...

**Comment by manatlan** [comment]
btw, in future guy's version : I will try, when autoreload is on, to don't kill the client window (run/runCef) and refresh just the current one ... to speedup the process
