### ISSUE TITLE
How to load internal pages/links

### ISSUE THREAD

**Issue by IronBrotherz** [manatlan/wuy#3]
If I have for example in my html page:

` <a href="about.html">about page</a>`

When I click the link, the app closes.  How can I do something basic like this?

**Comment by manatlan** [comment]
In fact, it's logical ...

The window create a link with the server (the socket). And if you navigate away, you broke that link, so the server think you close the window, and stop all.

To avoid that kind of thing, you shouldn't try to navigate in the main window.
But you can use alternatives like an iframe, or use Ajax things to replace content of a div.

Is it clear for you ?

**Comment by IronBrotherz** [comment]
Yes, thank you!
