### ISSUE TITLE
How can I get real path of local file?

### ISSUE THREAD

**Issue by zyhwhu2009** [manatlan/wuy#6]
Hi,
Very nice tool! I use ell first and now try to use wuy, and I think it's more convenient and powerful.
How can I get real path of local file by <input type="file"/> in html? 
Thanks.

**Comment by manatlan** [comment]
hi thanks ....
There is currently no way to get ...(but last day, I feel the need of that
too)
btw, you can do easily by requesting the server ...
create a rpc method serverside, "getPath", and request it clientslide
wuy.getPath() ...

**Comment by zyhwhu2009** [comment]
Thank you for your prompt reply. I am new and still do not know how to create a rpc method serverside. could you give me a example or reference.
btw, how could I upload a file as a server mode? method emit?
Thanks!!!!

**Comment by manatlan** [comment]
Here is an exemple, for serverside mode (note that : it doesn't have sense in window mode, because client & server are on the same host)

that's a drag'n'drop example : drop a **text** file on the page, it will be sent to the server via the upload rpc method ;-)

if you want to do it with binary file, just replace with `readAsDataURL` ... and decode dataurl on serverside !

```python
# -*- coding: utf-8 -*-
import wuy

class index(wuy.Server):
    """
    <script>
    function mydragover(e) {
        e.target.style.background = "red";
        e.preventDefault()
    }
    function mydragend(e) {
        e.target.style.background = "white";
    }
    function mydrop(e) {
        e.target.style.background = "white";
        for(var f of e.dataTransfer.files) {
            var reader = new FileReader();
            reader.onload = function (ee) {
                wuy.upload(f.name,ee.target.result)
            };
            // reader.readAsDataURL(f);
            reader.readAsText(f);
        }
        e.preventDefault()
    }
    </script>
    <body
        ondragover="mydragover(event)"
        ondragleave="mydragend(event)"
        ondragend="mydragend(event)"
        ondrop="mydrop(event)">drop on me</body>
    """

    def upload(self,name,content):
        # here, on server side : save the file 'name', with the text 'content',
        print("server:",name,content)

if __name__=="__main__":
    index()
```
