### ISSUE TITLE
Is it possible to write the html/js/css in files and load them into wuy?

### ISSUE THREAD

**Issue by elieobeid7** [manatlan/wuy#9]
Is it possible to write

index.html styles.css and script.js and just load them into wuy, because I don't like writing html inside a python function

**Comment by manatlan** [comment]
for sure !

Look https://github.com/manatlan/wuy/blob/master/an_app4.py ... it uses the doSomething file here : https://github.com/manatlan/wuy/blob/master/web/doSomething.html ...
everything that is in web will be visible from http (including js/css) ... and will be freezed in exe too

**Comment by elieobeid7** [comment]
So the python function should have the same name as the html file name, wow that's so beautiful thank you so much

**Comment by manatlan** [comment]
The class name should be the same name as the HTML file

Le lun. 28 janv. 2019 à 20:33, Elie Obeid <notifications@github.com> a
écrit :
